#ifndef CONFIG_H
#define CONFIG_H

// Devices & Robot
#define INERTIAL_SENSOR PORT18
#define MOTOR_LEFT_1 PORT6, BLUE_6, true
#define MOTOR_LEFT_2 PORT10, BLUE_6, true
#define MOTOR_LEFT_3 PORT9, BLUE_6
#define MOTOR_RIGHT_1 PORT20, BLUE_6
#define MOTOR_RIGHT_2 PORT16, BLUE_6
#define MOTOR_RIGHT_3 PORT17, BLUE_6, true

// Odometry
#define WHEEL_RADIUS 3.25

#define LEFT_ENCODER PORT1
#define RIGHT_ENCODER PORT2
#define SIDEWAYS_ENCODER PORT6

#define LEFT_TRACKER_OFFSET 5.125
#define RIGHT_TRACKER_OFFSET 5
#define SIDEWAYS_TRACKER_OFFSET 6.5

// PID Constants
#define DRIVE_PID_kP 0.4f
#define DRIVE_PID_kI 0.0
#define DRIVE_PID_kD 0.5
#define DRIVE_PID_ACCURACY 1.0

#define HEADING_PID_kP 0.5
#define HEADING_PID_kI 0.0
#define HEADING_PID_kD 0.9
#define HEADING_PID_ACCURACY 1.0

#define TURN_PID_kP 0.0
#define TURN_PID_kI 0.0
#define TURN_PID_kD 0.0
#define TURN_PID_ACCURACY 0.0

#define SWING_PID_kP 0.0
#define SWING_PID_kI 0.0
#define SWING_PID_kD 0.0
#define SWING_PID_ACCURACY 0.0

#endif  // CONFIG_H